// ============================================================
//  Stéphane Maarek Udemy course curricula (fetched 2026-09-25)
//  Used by the Today screen + lecture tracker.
//  lectures: [title, seconds, kind]  kind: v=video h=hands-on video
//            a=article q=section quiz p=practice test r=role-play
//  pace: trivial | skim (2x, already covered) | normal (1.5x) | deep (1.25x, heavy exam weight)
// ============================================================

const COURSES = {
  clf: {
    title: "Ultimate AWS Certified Cloud Practitioner CLF-C02",
    author: "Stéphane Maarek",
    url: "https://www.udemy.com/course/aws-certified-cloud-practitioner-new/",
    totalMinutes: 867,
    sections: [
      { id: "clf-01", n: 1, title: "Introduction", minutes: 14, pace: "normal", lectures: [
        ["Course Introduction",294,"v"],
        ["Creating an AWS Account",215,"v"],
        ["AWS Account Activation Troubleshooting",125,"a"],
        ["Important Message",59,"v"],
        ["About your instructor",159,"v"],
      ] },
      { id: "clf-02", n: 2, title: "Code & Slides Download", minutes: 0, pace: "trivial", lectures: [
        ["Code & Slides Download",7,"a"],
      ] },
      { id: "clf-03", n: 3, title: "What is Cloud Computing?", minutes: 32, pace: "normal", lectures: [
        ["Traditional IT Overview",389,"v"],
        ["What is Cloud Computing?",472,"v"],
        ["The Different Types of Cloud Computing",199,"v"],
        ["AWS Cloud Overview",481,"v"],
        ["[Important] AWS Console UI Update",74,"v"],
        ["Tour of the Console & Services in AWS",232,"v"],
        ["Shared Responsibility Model & AWS Acceptable Policy",96,"v"],
        ["What is Cloud Computing Quiz",0,"q"],
        ["Explaining AWS Cloud Concepts to Non-Technical Stakeholders",0,"r"],
      ] },
      { id: "clf-04", n: 4, title: "IAM - Identity and Access Management", minutes: 58, pace: "normal", lectures: [
        ["IAM Introduction: Users, Groups, Policies",202,"v"],
        ["IAM Users & Groups Hands On",383,"h"],
        ["AWS Console Simultaneous Sign-in",108,"v"],
        ["IAM Policies",170,"v"],
        ["IAM Policies Hands On",481,"h"],
        ["IAM MFA Overview",250,"v"],
        ["IAM MFA Hands On",241,"h"],
        ["AWS Access Keys, CLI and SDK",243,"v"],
        ["AWS CLI Setup on Windows",105,"v"],
        ["AWS CLI Setup on Mac",88,"v"],
        ["AWS CLI Setup on Linux",90,"v"],
        ["AWS CLI Hands On",230,"h"],
        ["AWS CloudShell",233,"v"],
        ["IAM Roles for AWS Services",99,"v"],
        ["IAM Roles Hands On",125,"h"],
        ["IAM Security Tools",54,"v"],
        ["IAM Security Tools Hands On",143,"h"],
        ["IAM Best Practices",89,"v"],
        ["Shared Responsibility Model for IAM",91,"v"],
        ["IAM Summary",65,"v"],
        ["Identity and Access Management Quiz",0,"q"],
        ["Communicating IAM and Security Best Practices to Non-Technical Stakeholders",0,"r"],
      ] },
      { id: "clf-05", n: 5, title: "EC2 - Elastic Compute Cloud", minutes: 82, pace: "normal", lectures: [
        ["AWS Budget Setup",305,"v"],
        ["EC2 Basics",212,"v"],
        ["Create an EC2 Instance with EC2 User Data to have a Website Hands On",828,"h"],
        ["EC2 Instance Types Basics",291,"v"],
        ["Security Groups & Classic Ports Overview",438,"v"],
        ["Security Groups Hands On",285,"h"],
        ["SSH Overview",167,"v"],
        ["How to SSH using Linux or Mac",425,"v"],
        ["How to SSH using Windows",368,"v"],
        ["How to SSH using Windows 10",301,"v"],
        ["SSH Troubleshooting",83,"a"],
        ["EC2 Instance Connect",195,"v"],
        ["EC2 Instance Roles Demo",259,"v"],
        ["EC2 Instance Purchasing Options",588,"v"],
        ["Shared Responsibility Model for EC2",85,"v"],
        ["EC2 Summary",90,"v"],
        ["EC2 Quiz",0,"q"],
        ["Explaining Amazon EC2 to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-06", n: 6, title: "EC2 Instance Storage", minutes: 42, pace: "normal", lectures: [
        ["EBS Overview",287,"v"],
        ["About EBS Multi-Attach",24,"a"],
        ["EBS Hands On",334,"h"],
        ["EBS Snapshots Overview",160,"v"],
        ["EBS Snapshots Hands On",218,"h"],
        ["AMI Overview",165,"v"],
        ["AMI Hands On",299,"h"],
        ["EC2 Image Builder Overview",154,"v"],
        ["EC2 Instance Store",167,"v"],
        ["EFS Overview",261,"v"],
        ["Shared Responsibility Model for EC2 Storage",104,"v"],
        ["Amazon FSx Overview",184,"v"],
        ["EC2 Instance Storage Summary",92,"v"],
        ["Section Cleanup",94,"v"],
        ["EC2 Instance Storage Quiz",0,"q"],
        ["Explaining EC2 Storage Concepts to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-07", n: 7, title: "ELB & ASG - Elastic Load Balancing & Auto Scaling Groups", minutes: 39, pace: "normal", lectures: [
        ["High Availability, Scalability, Elasticity",383,"v"],
        ["Elastic Load Balancing (ELB) Overview",390,"v"],
        ["Application Load Balancer (ALB) Hands On",514,"h"],
        ["Auto Scaling Groups (ASG) Overview",182,"v"],
        ["Auto Scaling Groups (ASG) Hands On",522,"h"],
        ["Auto Scaling Groups (ASG) Strategies",174,"v"],
        ["Section Cleanup",69,"v"],
        ["ELB & ASG Summary",117,"v"],
        ["ELB & ASG Quiz",0,"q"],
        ["Explaining High Availability and Scalability with AWS Services",0,"r"],
      ] },
      { id: "clf-08", n: 8, title: "Amazon S3", minutes: 55, pace: "normal", lectures: [
        ["S3 Overview",330,"v"],
        ["S3 Hands On",449,"h"],
        ["S3 Security: Bucket Policy",303,"v"],
        ["S3 Security: Bucket Policy Hands On",196,"h"],
        ["S3 Website Overview",67,"v"],
        ["S3 Website Hands On",118,"h"],
        ["S3 Versioning Overview",73,"v"],
        ["S3 Versioning Hands On",257,"h"],
        ["S3 Replication Overview",85,"v"],
        ["S3 Replication Hands On",292,"h"],
        ["S3 Storage Classes Overview",372,"v"],
        ["S3 Storage Classes Hands On",217,"h"],
        ["S3 Express One Zone",110,"v"],
        ["S3 Encryption",61,"v"],
        ["IAM Access Analyzer for S3",62,"v"],
        ["Shared Responsibility Model for S3",67,"v"],
        ["Storage Gateway Overview",158,"v"],
        ["S3 Summary",87,"v"],
        ["S3 Quiz",0,"q"],
        ["Explaining Amazon S3 Features to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-09", n: 9, title: "Databases & Analytics", minutes: 47, pace: "normal", lectures: [
        ["Databases Introduction",343,"v"],
        ["RDS & Aurora Overview",294,"v"],
        ["RDS Hands On",411,"h"],
        ["RDS Deployments Options",221,"v"],
        ["ElastiCache Overview",123,"v"],
        ["DynamoDB Overview",181,"v"],
        ["DynamoDB Hands On",186,"h"],
        ["DynamoDB Global Tables",77,"v"],
        ["Redshift Overview",164,"v"],
        ["EMR Overview",81,"v"],
        ["Athena Overview",80,"v"],
        ["QuickSight Overview",56,"v"],
        ["DocumentDB Overview",75,"v"],
        ["Neptune Overview",83,"v"],
        ["Timestream Overview",71,"v"],
        ["Managed Blockchain Overview",49,"v"],
        ["Glue Overview",125,"v"],
        ["DMS Overview",78,"v"],
        ["Databases & Analytics Summary",138,"v"],
        ["Databases & Analytics Quiz",0,"q"],
        ["Explaining AWS Database Options to Business Stakeholders",0,"r"],
      ] },
      { id: "clf-10", n: 10, title: "Other Compute Services: ECS, Lambda, Batch, Lightsail", minutes: 37, pace: "normal", lectures: [
        ["What is Docker?",207,"v"],
        ["ECS, Fargate & ECR Overview",181,"v"],
        ["Amazon EKS",101,"v"],
        ["Serverless Introduction",125,"v"],
        ["Lambda Overview",375,"v"],
        ["Lambda Hands On",397,"h"],
        ["API Gateway Overview",88,"v"],
        ["Batch Overview",185,"v"],
        ["Lightsail Overview",107,"v"],
        ["Lightsail Hands On",277,"h"],
        ["Other Compute - Summary",162,"v"],
        ["Other Compute Services Quiz",0,"q"],
        ["Explaining AWS Compute Options to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-11", n: 11, title: "Deployments & Managing Infrastructure at Scale", minutes: 46, pace: "normal", lectures: [
        ["CloudFormation Overview",211,"v"],
        ["CloudFormation Hands On",512,"h"],
        ["CDK Overview",119,"v"],
        ["Beanstalk Overview",253,"v"],
        ["Beanstalk Hands On",501,"h"],
        ["CodeDeploy Overview",100,"v"],
        ["CodeCommit Overview",63,"v"],
        ["CodeBuild Overview",66,"v"],
        ["CodePipeline Overview",97,"v"],
        ["CodeArtifact Overview",84,"v"],
        ["Systems Manager (SSM) Overview",145,"v"],
        ["SSM Session Manager",345,"v"],
        ["SSM Parameter Store",142,"v"],
        ["Deployment Summary",126,"v"],
        ["Deployments & Managing Infrastructure at Scale in AWS Quiz",0,"q"],
        ["Explaining AWS Automation Benefits to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-12", n: 12, title: "Leveraging the AWS Global Infrastructure", minutes: 49, pace: "normal", lectures: [
        ["Why Global Applications?",341,"v"],
        ["Route 53 Overview",268,"v"],
        ["Route 53 Hands On",429,"h"],
        ["CloudFront Overview",322,"v"],
        ["CloudFront Hands On",338,"h"],
        ["S3 Transfer Acceleration",142,"v"],
        ["AWS Global Accelerator",295,"v"],
        ["AWS Outposts",158,"v"],
        ["AWS WaveLength",116,"v"],
        ["AWS Local Zones",233,"v"],
        ["Global Applications Architecture",155,"v"],
        ["Leveraging the AWS Global Infrastructure Summary",117,"v"],
        ["Leveraging the AWS Global Infrastructure Quiz",0,"q"],
        ["Explaining AWS Global Services for Enhanced Application Performance",0,"r"],
      ] },
      { id: "clf-13", n: 13, title: "Cloud Integrations", minutes: 18, pace: "normal", lectures: [
        ["Cloud Integrations Overview",117,"v"],
        ["SQS Overview",224,"v"],
        ["SQS Hands On",167,"h"],
        ["Kinesis Overview",79,"v"],
        ["SNS Overview",118,"v"],
        ["SNS Hands On",144,"h"],
        ["Amazon MQ Overview",123,"v"],
        ["Cloud Integrations Summary",91,"v"],
        ["Cloud Integrations Quiz",0,"q"],
        ["Explaining AWS Messaging and Streaming Services to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-14", n: 14, title: "Cloud Monitoring", minutes: 39, pace: "normal", lectures: [
        ["CloudWatch Metrics & CloudWatch Alarms Overview",216,"v"],
        ["CloudWatch Metrics & CloudWatch Alarms Hands On",461,"h"],
        ["CloudWatch Logs Overview",134,"v"],
        ["CloudWatch Logs Hands On",171,"h"],
        ["EventBridge Overview (formerly CloudWatch Events)",187,"v"],
        ["EventBridge Hands On",455,"h"],
        ["CloudTrail Overview",126,"v"],
        ["CloudTrail Hands On",90,"h"],
        ["X-Ray Overview",131,"v"],
        ["AWS Health Dashboard",118,"v"],
        ["AWS Health Dashboard - Hands On",140,"h"],
        ["Cloud Monitoring Summary",89,"v"],
        ["Cloud Monitoring Quiz",0,"q"],
        ["Monitoring and Auditing AWS Activity",0,"r"],
      ] },
      { id: "clf-15", n: 15, title: "VPC & Networking", minutes: 35, pace: "normal", lectures: [
        ["VPC Overview",80,"v"],
        ["IP Addresses in AWS",179,"v"],
        ["VPC, Subnet, Internet Gateway & NAT Gateways",214,"v"],
        ["VPC, Subnet, Internet Gateway & NAT Gateways - Hands On",386,"h"],
        ["Security Groups & Network Access Control List (NACL)",255,"v"],
        ["VPC Flow Logs & VPC Peering",219,"v"],
        ["VPC Endpoints - Interface & Gateway (S3 & DynamoDB)",157,"v"],
        ["PrivateLink",124,"v"],
        ["Direct Connect & Site-to-Site VPN",156,"v"],
        ["Client VPN",80,"v"],
        ["Transit Gateway Overview",74,"v"],
        ["VPC & Networking Summary",169,"v"],
        ["VPC & Networking Quiz",0,"q"],
        ["Explaining AWS Networking Concepts to Business Stakeholders",0,"r"],
      ] },
      { id: "clf-16", n: 16, title: "Security & Compliance", minutes: 56, pace: "normal", lectures: [
        ["Shared Responsibility Model: Reminders & Examples",268,"v"],
        ["DDoS Protection: WAF & Shield",283,"v"],
        ["AWS Network Firewall",50,"v"],
        ["AWS Firewall Manager",73,"v"],
        ["Penetration Testing",108,"v"],
        ["Encryption with KMS & CloudHSM",314,"v"],
        ["Encryption with KMS & CloudHSM Hands On",274,"h"],
        ["AWS Certificate Manager (ACM) Overview",89,"v"],
        ["Secrets Manager Overview",168,"v"],
        ["Artifact Overview",119,"v"],
        ["GuardDuty Overview",152,"v"],
        ["Inspector Overview",148,"v"],
        ["Config Overview",406,"v"],
        ["Macie Overview",63,"v"],
        ["Security Hub Overview",163,"v"],
        ["Amazon Detective Overview",69,"v"],
        ["AWS Abuse",71,"v"],
        ["Root User Privileges",123,"v"],
        ["IAM Access Analyzer",224,"v"],
        ["Security & Compliance Summary",179,"v"],
        ["Security & Compliance Quiz",0,"q"],
        ["Explaining AWS Security Services to a Concerned Business Stakeholder",0,"r"],
      ] },
      { id: "clf-17", n: 17, title: "Machine Learning", minutes: 19, pace: "normal", lectures: [
        ["Rekognition Overview",111,"v"],
        ["Transcribe Overview",177,"v"],
        ["Polly Overview",72,"v"],
        ["Translate Overview",35,"v"],
        ["Lex + Connect Overview",115,"v"],
        ["Comprehend Overview",108,"v"],
        ["SageMaker AI Overview",209,"v"],
        ["Kendra Overview",82,"v"],
        ["Personalize Overview",96,"v"],
        ["Textract Overview",56,"v"],
        ["Machine Learning Summary",66,"v"],
        ["Machine Learning Quiz",0,"q"],
        ["Explaining AWS AI Services to a Non-Technical Business Stakeholder",0,"r"],
      ] },
      { id: "clf-18", n: 18, title: "Account Management, Billing & Support", minutes: 73, pace: "normal", lectures: [
        ["Organizations Overview",325,"v"],
        ["Organizations Hands On",599,"h"],
        ["Organizations Consolidated Billing",142,"v"],
        ["AWS Control Tower Overview",52,"v"],
        ["AWS Control Tower Hands On",427,"h"],
        ["AWS Resource Access Manager (AWS RAM)",85,"v"],
        ["AWS Service Catalog - Overview",101,"v"],
        ["Pricing Models of the Cloud",619,"v"],
        ["Savings Plan Overview",278,"v"],
        ["Compute Optimizer Overview",51,"v"],
        ["Billing & Costing Tools Overview",39,"v"],
        ["Estimating Costs in the Cloud - Pricing Calculator",142,"v"],
        ["Tracking Costs in the Cloud - Billing Dashboard, Cost Allocation Tags, Reports",532,"v"],
        ["Monitoring Costs in the Cloud - Billing Alarms & AWS Budgets",264,"v"],
        ["AWS Cost Anomaly Detection",70,"v"],
        ["AWS Service Quotas",71,"v"],
        ["AWS Trusted Advisor",198,"v"],
        ["Support Plans for AWS",195,"v"],
        ["Account Best Practices Summary",96,"v"],
        ["Billing Summary",80,"v"],
        ["Account Management, Billing & Support Quiz",0,"q"],
        ["Pricing Quiz",0,"q"],
        ["Explaining AWS Governance and Cost Optimization to Non-Technical Stakeholders",0,"r"],
      ] },
      { id: "clf-19", n: 19, title: "Advanced Identity", minutes: 9, pace: "normal", lectures: [
        ["Security Token Service (STS) Overview",102,"v"],
        ["Cognito Overview",67,"v"],
        ["Directory Services Overview",172,"v"],
        ["AWS IAM Identity Center",108,"v"],
        ["Advanced Identity - Summary",65,"v"],
        ["Advanced Identity Quiz",0,"q"],
        ["Explaining AWS Access Management Solutions to Business Stakeholders",0,"r"],
      ] },
      { id: "clf-20", n: 20, title: "Other Services", minutes: 35, pace: "normal", lectures: [
        ["Other Services - Section Intro",44,"v"],
        ["WorkSpaces Overview",109,"v"],
        ["AppStream 2.0 Overview",92,"v"],
        ["IoT Core Overview",73,"v"],
        ["AppSync",77,"v"],
        ["Amplify",91,"v"],
        ["AWS Infrastructure Composer",182,"v"],
        ["Device Farm Overview",75,"v"],
        ["AWS Backup Overview",60,"v"],
        ["Disaster Recovery Strategies",149,"v"],
        ["AWS Elastic Disaster Recovery (DRS)",108,"v"],
        ["Cloud Migration Strategies - The 7Rs",282,"v"],
        ["Application Discovery Service & Application Migration Service",183,"v"],
        ["AWS Migration Evaluator",83,"v"],
        ["AWS Migration Hub",79,"v"],
        ["AWS Fault Injection Simulator (FIS)",115,"v"],
        ["Step Functions",92,"v"],
        ["Ground Station",81,"v"],
        ["AWS Pinpoint",112,"v"],
        ["Other Services Quiz",0,"q"],
        ["Explaining AWS Cloud Migration and Disaster Recovery to a Business Stakeholder",0,"r"],
      ] },
      { id: "clf-21", n: 21, title: "AWS Architecting & Ecosystem", minutes: 50, pace: "normal", lectures: [
        ["AWS WhitePapers Well-Architected Framework",289,"v"],
        ["Pillar 1: Operational Excellence",212,"v"],
        ["Pillar 2: Security",253,"v"],
        ["Pillar 3: Reliability",194,"v"],
        ["Pillar 4: Performance Efficiency",204,"v"],
        ["Pillar 5: Cost Optimization",235,"v"],
        ["Pillar 6: Sustainability",136,"v"],
        ["AWS Well-Architected Tool",198,"v"],
        ["AWS Customer Carbon Footprint Tool",81,"v"],
        ["AWS Cloud Adoption Framework (CAF)",490,"v"],
        ["Right Sizing",101,"v"],
        ["AWS Ecosystem",347,"v"],
        ["AWS re:Post",87,"v"],
        ["AWS Knowledge Center",76,"v"],
        ["AWS Managed Services",116,"v"],
        ["AWS Architecting & Ecosystem Quiz",0,"q"],
        ["Explaining AWS Frameworks for Cloud Transformation",0,"r"],
      ] },
      { id: "clf-22", n: 22, title: "Preparing for the Exam + Practice Exam - AWS Certified Cloud Practitioner", minutes: 23, pace: "normal", lectures: [
        ["Words on Other Services",107,"v"],
        ["State of Learning Checkpoint - AWS Certified Cloud Practitioner",223,"v"],
        ["Exam Sample Question Walkthrough",338,"v"],
        ["Exam Tips - AWS Certified Cloud Practitioner",320,"v"],
        ["Exam Walkthrough and Signup",277,"v"],
        ["Save 50% on your AWS Exam Cost!",70,"v"],
        ["Get an Extra 30 Minutes on your AWS Exam - Non Native English Speakers only",64,"v"],
        ["Practice Exam - AWS Certified Cloud Practitioner",0,"p"],
      ] },
      { id: "clf-23", n: 23, title: "Congratulations - AWS Certified Cloud Practitioner", minutes: 9, pace: "trivial", lectures: [
        ["AWS Certification Paths",365,"v"],
        ["Congratulations",96,"v"],
        ["Bonus Lecture",73,"a"],
      ] },
    ],
  },
  saa: {
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03",
    author: "Stéphane Maarek",
    url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
    totalMinutes: 1635,
    sections: [
      { id: "saa-01", n: 1, title: "Introduction - AWS Certified Solutions Architect Associate", minutes: 15, pace: "skim", lectures: [
        ["Course Introduction - AWS Certified Solutions Architect Associate",230,"v"],
        ["PLEASE READ: Lectures you can skip if you took a course from me before",94,"a"],
        ["Creating an AWS Account",215,"v"],
        ["AWS Account Activation Troubleshooting",125,"a"],
        ["Important Message",59,"v"],
        ["About your instructor",159,"v"],
      ] },
      { id: "saa-02", n: 2, title: "Code & Slides Download", minutes: 0, pace: "trivial", lectures: [
        ["Slides and Code Download",15,"a"],
      ] },
      { id: "saa-03", n: 3, title: "Getting started with AWS", minutes: 13, pace: "skim", lectures: [
        ["AWS Cloud Overview - Regions & AZ",481,"v"],
        ["[Important] AWS Console UI Update",74,"v"],
        ["Tour of the AWS Console & Services in AWS",232,"v"],
      ] },
      { id: "saa-04", n: 4, title: "IAM & AWS CLI", minutes: 57, pace: "skim", lectures: [
        ["IAM Introduction: Users, Groups, Policies",202,"v"],
        ["IAM Users & Groups Hands On",383,"h"],
        ["AWS Console Simultaneous Sign-in",108,"v"],
        ["IAM Policies",170,"v"],
        ["IAM Policies Hands On",481,"h"],
        ["IAM MFA Overview",250,"v"],
        ["IAM MFA Hands On",241,"h"],
        ["AWS Access Keys, CLI and SDK",243,"v"],
        ["AWS CLI Setup on Windows",105,"v"],
        ["AWS CLI Setup on Mac OS X",88,"v"],
        ["AWS CLI Setup on Linux",90,"v"],
        ["AWS CLI Hands On",230,"h"],
        ["AWS CloudShell: Region Availability",12,"a"],
        ["AWS CloudShell",233,"v"],
        ["IAM Roles for AWS Services",99,"v"],
        ["IAM Roles Hands On",125,"h"],
        ["IAM Security Tools",54,"v"],
        ["IAM Security Tools Hands On",143,"h"],
        ["IAM Best Practices",89,"v"],
        ["IAM Summary",65,"v"],
        ["IAM & AWS CLI Quiz",0,"q"],
      ] },
      { id: "saa-05", n: 5, title: "EC2 Fundamentals", minutes: 97, pace: "skim", lectures: [
        ["AWS Budget Setup",305,"v"],
        ["EC2 Basics",212,"v"],
        ["Create an EC2 Instance with EC2 User Data to have a Website Hands On",828,"h"],
        ["EC2 Instance Types Basics",291,"v"],
        ["Security Groups & Classic Ports Overview",438,"v"],
        ["Security Groups Hands On",285,"h"],
        ["SSH Overview",167,"v"],
        ["How to SSH using Linux or Mac",425,"v"],
        ["How to SSH using Windows",368,"v"],
        ["How to SSH using Windows 10",301,"v"],
        ["SSH Troubleshooting",83,"a"],
        ["EC2 Instance Connect",195,"v"],
        ["EC2 Instance Roles Demo",259,"v"],
        ["EC2 Instance Purchasing Options",588,"v"],
        ["Spot Instances & Spot Fleet",532,"v"],
        ["EC2 Instances Launch Types Hands On",532,"h"],
        ["EC2 Fundamentals Quiz",0,"q"],
      ] },
      { id: "saa-06", n: 6, title: "EC2 - Solutions Architect Associate Level", minutes: 35, pace: "normal", lectures: [
        ["Private vs Public vs Elastic IP",282,"v"],
        ["Private vs Public vs Elastic IP Hands On",366,"h"],
        ["EC2 Placement Groups",415,"v"],
        ["EC2 Placement Groups - Hands On",102,"h"],
        ["Elastic Network Interfaces (ENI) - Overview",135,"v"],
        ["Elastic Network Interfaces (ENI) - Hands On",323,"h"],
        ["ENI - Extra Reading",21,"a"],
        ["EC2 Hibernate",193,"v"],
        ["EC2 Hibernate - Hands On",247,"h"],
        ["EC2 SAA Level Quiz",0,"q"],
      ] },
      { id: "saa-07", n: 7, title: "EC2 Instance Storage", minutes: 59, pace: "normal", lectures: [
        ["EBS Overview",287,"v"],
        ["EBS Hands On",334,"h"],
        ["EBS Snapshots",128,"v"],
        ["EBS Snapshots - Hands On",218,"h"],
        ["AMI Overview",165,"v"],
        ["AMI Hands On",299,"h"],
        ["EC2 Instance Store",167,"v"],
        ["EBS Volume Types",303,"v"],
        ["EBS Multi-Attach",105,"v"],
        ["EBS Encryption",227,"v"],
        ["Amazon EFS",318,"v"],
        ["Amazon EFS - Hands On",785,"h"],
        ["EFS vs EBS",131,"v"],
        ["EBS & EFS - Section Cleanup",91,"v"],
        ["EC2 Data Management Quiz",0,"q"],
      ] },
      { id: "saa-08", n: 8, title: "High Availability and Scalability: ELB & ASG", minutes: 94, pace: "deep", lectures: [
        ["High Availability and Scalability",305,"v"],
        ["Elastic Load Balancing (ELB) Overview",375,"v"],
        ["Application Load Balancer (ALB)",349,"v"],
        ["Application Load Balancer (ALB) - Hands On - Part 1",514,"h"],
        ["Application Load Balancer (ALB) - Hands On - Part 2",337,"h"],
        ["Network Load Balancer (NLB)",204,"v"],
        ["Network Load Balancer (NLB) - Hands On",363,"h"],
        ["Gateway Load Balancer (GWLB)",227,"v"],
        ["Elastic Load Balancer - Sticky Sessions",351,"v"],
        ["Elastic Load Balancer - Cross Zone Load Balancing",353,"v"],
        ["Elastic Load Balancer - SSL Certificates",364,"v"],
        ["Elastic Load Balancer - SSL Certificates - Hands On",119,"h"],
        ["Elastic Load Balancer - Connection Draining",142,"v"],
        ["Auto Scaling Groups (ASG) Overview",282,"v"],
        ["Auto Scaling Groups Hands On",536,"h"],
        ["Auto Scaling Groups - Scaling Policies",263,"v"],
        ["Auto Scaling Groups - Scaling Policies Hands On",555,"h"],
        ["High Availability & Scalability Quiz",0,"q"],
      ] },
      { id: "saa-09", n: 9, title: "AWS Fundamentals: RDS + Aurora + ElastiCache", minutes: 70, pace: "deep", lectures: [
        ["Amazon RDS Overview",218,"v"],
        ["RDS Read Replicas vs Multi AZ",442,"v"],
        ["Amazon RDS Hands On",524,"h"],
        ["RDS Custom for Oracle and Microsoft SQL Server",109,"v"],
        ["Amazon Aurora",387,"v"],
        ["Amazon Aurora - Hands On",502,"h"],
        ["Amazon Aurora - Advanced Concepts",451,"v"],
        ["RDS & Aurora - Backup and Monitoring",336,"v"],
        ["RDS  Security",152,"v"],
        ["RDS Proxy",272,"v"],
        ["ElastiCache Overview",282,"v"],
        ["ElastiCache Hands On",300,"h"],
        ["ElastiCache for Solution Architects",180,"v"],
        ["List of Ports to be familiar with",29,"a"],
        ["RDS, Aurora, & ElastiCache Quiz",0,"q"],
      ] },
      { id: "saa-10", n: 10, title: "Route 53", minutes: 85, pace: "deep", lectures: [
        ["What is a DNS ?",384,"v"],
        ["Route 53 Overview",378,"v"],
        ["Route 53 - Registering a domain",204,"v"],
        ["Route 53 - Creating our first records",236,"v"],
        ["Route 53 - EC2 Setup",340,"v"],
        ["Route 53 - TTL",328,"v"],
        ["Route 53 CNAME vs Alias",420,"v"],
        ["Routing Policy - Simple",245,"v"],
        ["Routing Policy - Weighted",302,"v"],
        ["Routing Policy - Latency",279,"v"],
        ["Route 53 - Health Checks",294,"v"],
        ["Route 53 - Health Checks Hands On",279,"h"],
        ["Routing Policy - Failover",252,"v"],
        ["Routing Policy - Geolocation",255,"v"],
        ["Routing Policy - Geoproximity",201,"v"],
        ["Routing Policy - IP-based",105,"v"],
        ["Routing Policy - Multi Value",222,"v"],
        ["3rd Party Domains & Route 53",144,"v"],
        ["Route 53 Resolvers & Hybrid DNS",176,"v"],
        ["Route 53 - Section Cleanup",81,"v"],
        ["Route 53 Quiz",0,"q"],
      ] },
      { id: "saa-11", n: 11, title: "Classic Solutions Architecture Discussions", minutes: 43, pace: "deep", lectures: [
        ["Solutions Architecture Discussions Overview",72,"v"],
        ["WhatsTheTime.com",673,"v"],
        ["MyClothes.com",578,"v"],
        ["MyWordPress.com",277,"v"],
        ["Instantiating applications quickly",173,"v"],
        ["Beanstalk Overview",310,"v"],
        ["Beanstalk Hands On",501,"h"],
        ["Classic Solutions Architecture Discussions Quiz",0,"q"],
      ] },
      { id: "saa-12", n: 12, title: "Amazon S3 Introduction", minutes: 50, pace: "skim", lectures: [
        ["S3 Overview",330,"v"],
        ["S3 Hands On",449,"h"],
        ["S3 Security: Bucket Policy",303,"v"],
        ["S3 Security: Bucket Policy Hands On",196,"h"],
        ["S3 Website Overview",67,"v"],
        ["S3 Website Hands On",118,"h"],
        ["S3 Versioning",73,"v"],
        ["S3 Versioning - Hands On",257,"h"],
        ["S3 Replication",85,"v"],
        ["S3 Replication Notes",57,"v"],
        ["S3 Replication - Hands On",389,"h"],
        ["S3 Storage Classes Overview",372,"v"],
        ["S3 Storage Classes Hands On",217,"h"],
        ["S3 Express One Zone",110,"v"],
        ["Amazon S3 Quiz",0,"q"],
      ] },
      { id: "saa-13", n: 13, title: "Advanced Amazon S3", minutes: 30, pace: "normal", lectures: [
        ["S3 Lifecycle Rules (with S3 Analytics)",260,"v"],
        ["S3 Lifecycle Rules - Hands On",144,"h"],
        ["S3 Requester Pays",98,"v"],
        ["S3 Event Notifications",210,"v"],
        ["S3 Event Notifications - Hands On",342,"h"],
        ["S3 Performance",293,"v"],
        ["S3 Batch Operations",121,"v"],
        ["S3 Storage Lens",338,"v"],
        ["Amazon S3 Advanced Quiz",0,"q"],
      ] },
      { id: "saa-14", n: 14, title: "Amazon S3 Security", minutes: 54, pace: "deep", lectures: [
        ["S3 Encryption",485,"v"],
        ["About DSSE-KMS",18,"a"],
        ["S3 Encryption - Hands On",294,"h"],
        ["S3 Default Encryption",80,"v"],
        ["S3 CORS",259,"v"],
        ["S3 CORS Hands On",443,"h"],
        ["S3 MFA Delete",84,"v"],
        ["S3 MFA Delete Hands On",385,"h"],
        ["S3 Access Logs",76,"v"],
        ["S3 Access Logs - Hands On",212,"h"],
        ["S3 Pre-signed URLs",110,"v"],
        ["S3 Pre-signed URLs - Hands On",108,"h"],
        ["Glacier Vault Lock & S3 Object Lock",253,"v"],
        ["S3 Access Points",214,"v"],
        ["S3 Object Lambda",190,"v"],
        ["Amazon S3 Security Quiz",0,"q"],
      ] },
      { id: "saa-15", n: 15, title: "CloudFront & AWS Global Accelerator", minutes: 33, pace: "normal", lectures: [
        ["CloudFront Overview",322,"v"],
        ["CloudFront with S3 - Hands On",338,"h"],
        ["CloudFront - ALB/EC2 as an Origin",156,"v"],
        ["CloudFront - Geo Restriction",99,"v"],
        ["CloudFront - Cache Invalidation",160,"v"],
        ["AWS Global Accelerator - Overview",366,"v"],
        ["AWS Global Accelerator - Hands On",529,"h"],
        ["CloudFront & AWS Global Accelerator Quiz",0,"q"],
      ] },
      { id: "saa-16", n: 16, title: "AWS Storage Extras", minutes: 37, pace: "normal", lectures: [
        ["AWS Snow Family Overview",175,"v"],
        ["AWS Snow Family Hands On",137,"h"],
        ["Architecture: Snowball into Glacier",37,"v"],
        ["Amazon FSx",502,"v"],
        ["Amazon FSx - Hands On",176,"h"],
        ["Storage Gateway Overview",486,"v"],
        ["Storage Gateway Hands On",127,"h"],
        ["AWS Transfer Family",139,"v"],
        ["DataSync - Overview",253,"v"],
        ["All AWS Storage Options Compared",214,"v"],
        ["AWS Storage Extras Quiz",0,"q"],
      ] },
      { id: "saa-17", n: 17, title: "Decoupling applications: SQS, SNS, Kinesis, Active MQ", minutes: 81, pace: "deep", lectures: [
        ["Introduction to Messaging",165,"v"],
        ["Amazon SQS - Standard Queues Overview",633,"v"],
        ["SQS - Standard Queue Hands On",387,"h"],
        ["SQS - Message Visibility Timeout",318,"v"],
        ["SQS - Long Polling",89,"v"],
        ["SQS - FIFO Queues",208,"v"],
        ["SQS + Auto Scaling Group",273,"v"],
        ["Amazon Simple Notification Service (AWS SNS)",258,"v"],
        ["SNS and SQS -  Fan Out Pattern",356,"v"],
        ["SNS - Hands On",275,"h"],
        ["Amazon Kinesis Data Streams",252,"v"],
        ["Amazon Kinesis Data Streams - Hands On",578,"h"],
        ["Amazon Data Firehose",243,"v"],
        ["Amazon Data Firehose - Hands On",472,"h"],
        ["SQS vs SNS vs Kinesis",180,"v"],
        ["Amazon MQ",162,"v"],
        ["Messaging & Integration Quiz",0,"q"],
      ] },
      { id: "saa-18", n: 18, title: "Containers on AWS: ECS, Fargate, ECR & EKS", minutes: 50, pace: "normal", lectures: [
        ["Docker Introduction",310,"v"],
        ["Amazon ECS",425,"v"],
        ["Creating ECS Cluster - Hands On",356,"h"],
        ["Creating ECS Service - Hands On",585,"h"],
        ["Amazon ECS - Auto Scaling",201,"v"],
        ["Amazon ECS - Solutions Architectures",189,"v"],
        ["Amazon ECS - Clean Up - Hands On",86,"h"],
        ["Amazon ECR",98,"v"],
        ["Amazon EKS - Overview",238,"v"],
        ["Amazon EKS - Hands On",496,"h"],
        ["Containers on AWS Quiz",0,"q"],
      ] },
      { id: "saa-19", n: 19, title: "Serverless Overviews from a Solution Architect Perspective", minutes: 83, pace: "deep", lectures: [
        ["About the Serverless Section",21,"a"],
        ["Serverless Introduction",139,"v"],
        ["Lambda Overview",428,"v"],
        ["Lambda Hands-On",397,"h"],
        ["Lambda Limits",104,"v"],
        ["Lambda Concurrency",361,"v"],
        ["Lambda Concurrency - Hands On",159,"h"],
        ["Lambda SnapStart",81,"v"],
        ["Lambda@Edge & CloudFront Functions",338,"v"],
        ["Lambda in VPC",192,"v"],
        ["RDS - Invoking Lambda & Event Notifications",155,"v"],
        ["Amazon DynamoDB",321,"v"],
        ["Amazon DynamoDB - Hands-On",287,"h"],
        ["Amazon DynamoDB - Advanced Features",514,"v"],
        ["API Gateway Overview",397,"v"],
        ["API Gateway Basics Hands-On",619,"h"],
        ["Step Functions",92,"v"],
        ["Amazon Cognito Overview",392,"v"],
        ["Serverless Overview Quiz",0,"q"],
      ] },
      { id: "saa-20", n: 20, title: "Serverless Solution Architecture Discussions", minutes: 16, pace: "normal", lectures: [
        ["Mobile Application: MyTodoList",285,"v"],
        ["Serverless Website: MyBlog.com",338,"v"],
        ["MicroServices Architecture",231,"v"],
        ["Software updates distribution",129,"v"],
        ["Serverless Solutions Architecture Discussions Quiz",0,"q"],
      ] },
      { id: "saa-21", n: 21, title: "Databases in AWS", minutes: 25, pace: "skim", lectures: [
        ["Choosing the right database",201,"v"],
        ["RDS",169,"v"],
        ["Aurora",161,"v"],
        ["ElastiCache",103,"v"],
        ["DynamoDB",223,"v"],
        ["S3",170,"v"],
        ["DocumentDB",75,"v"],
        ["Neptune",174,"v"],
        ["Keyspaces (for Apache Cassandra)",82,"v"],
        ["Timestream",137,"v"],
        ["Databases in AWS Quiz",0,"q"],
      ] },
      { id: "saa-22", n: 22, title: "Data & Analytics", minutes: 48, pace: "normal", lectures: [
        ["Athena",327,"v"],
        ["Athena Hands On",340,"h"],
        ["Redshift",404,"v"],
        ["OpenSearch (ex: ElasticSearch)",231,"v"],
        ["EMR",167,"v"],
        ["QuickSight",239,"v"],
        ["Glue",244,"v"],
        ["Lake Formation",246,"v"],
        ["Amazon Managed Service for Apache Flink",101,"v"],
        ["Amazon Managed Service for Apache Flink - Hands On",123,"h"],
        ["MSK - Managed Streaming for Apache Kafka",230,"v"],
        ["Big Data Ingestion Pipeline",251,"v"],
        ["Data & Analytics Quiz",0,"q"],
      ] },
      { id: "saa-23", n: 23, title: "Machine Learning", minutes: 26, pace: "skim", lectures: [
        ["Rekognition Overview",226,"v"],
        ["Transcribe Overview",177,"v"],
        ["Polly Overview",252,"v"],
        ["Translate Overview",35,"v"],
        ["Lex + Connect Overview",115,"v"],
        ["Comprehend Overview",108,"v"],
        ["Comprehend Medical Overview",124,"v"],
        ["SageMaker AI Overview",209,"v"],
        ["Kendra Overview",82,"v"],
        ["Personalize Overview",96,"v"],
        ["Textract Overview",56,"v"],
        ["Machine Learning Summary",66,"v"],
        ["Machine Learning Quiz",0,"q"],
      ] },
      { id: "saa-24", n: 24, title: "AWS Monitoring & Audit: CloudWatch, CloudTrail & Config", minutes: 79, pace: "normal", lectures: [
        ["AWS Monitoring - Section Introduction",38,"v"],
        ["CloudWatch Metrics",249,"v"],
        ["CloudWatch Logs",361,"v"],
        ["CloudWatch Logs - Hands On",530,"h"],
        ["CloudWatch Logs - Live Tail - Hands On",120,"h"],
        ["CloudWatch Agent & CloudWatch Logs Agent",196,"v"],
        ["CloudWatch Alarms",253,"v"],
        ["CloudWatch Alarms Hands On",278,"h"],
        ["CloudWatch Network Synthetic Monitor",60,"v"],
        ["EventBridge Overview (formerly CloudWatch Events)",419,"v"],
        ["Amazon EventBridge - Hands On",358,"h"],
        ["CloudWatch Insights and Operational Visibility",338,"v"],
        ["CloudTrail Overview",342,"v"],
        ["CloudTrail Hands On",90,"h"],
        ["CloudTrail - EventBridge Integration",98,"v"],
        ["AWS Config - Overview",284,"v"],
        ["AWS Config - Hands On",577,"h"],
        ["CloudTrail vs CloudWatch vs Config",149,"v"],
        ["Monitoring & Auditing Quiz",0,"q"],
      ] },
      { id: "saa-25", n: 25, title: "Identity and Access Management (IAM) - Advanced", minutes: 49, pace: "normal", lectures: [
        ["Organizations - Overview",390,"v"],
        ["Organizations - Hands On",599,"h"],
        ["Organizations - Tag Policies",86,"v"],
        ["IAM - Advanced Policies",256,"v"],
        ["IAM - Resource-based Policies vs IAM Roles",217,"v"],
        ["IAM - Policy Evaluation Logic",410,"v"],
        ["AWS IAM Identity Center",405,"v"],
        ["AWS Directory Services",358,"v"],
        ["AWS Directory Services - Hands On",79,"h"],
        ["AWS Control Tower",168,"v"],
        ["IAM Advanced Quiz",0,"q"],
      ] },
      { id: "saa-26", n: 26, title: "AWS Security & Encryption: KMS, SSM Parameter Store, Shield, WAF", minutes: 86, pace: "deep", lectures: [
        ["AWS Security - Section Introduction",44,"v"],
        ["Encryption 101",239,"v"],
        ["KMS Overview",448,"v"],
        ["KMS Hands On w/ CLI",571,"h"],
        ["KMS - Multi-Region Keys",371,"v"],
        ["S3 Replication with Encryption",100,"v"],
        ["Encrypted AMI Sharing Process",93,"v"],
        ["SSM Parameter Store Overview",256,"v"],
        ["SSM Parameter Store Hands On (CLI)",415,"h"],
        ["AWS Secrets Manager - Overview",130,"v"],
        ["AWS Secrets Manager - Hands On",240,"h"],
        ["AWS Certificate Manager (ACM)",462,"v"],
        ["AWS CloudHSM",286,"v"],
        ["Web Application Firewall (WAF)",181,"v"],
        ["Shield - DDoS Protection",124,"v"],
        ["Firewall Manager",162,"v"],
        ["WAF & Shield - Hands On",348,"h"],
        ["DDoS Protection Best Practices",353,"v"],
        ["Amazon GuardDuty",152,"v"],
        ["Amazon Inspector",148,"v"],
        ["Amazon Macie",63,"v"],
        ["AWS Security & Encryption Quiz",0,"q"],
      ] },
      { id: "saa-27", n: 27, title: "Networking - VPC", minutes: 160, pace: "deep", lectures: [
        ["Section Introduction",65,"v"],
        ["CIDR, Private vs Public IP",400,"v"],
        ["Default VPC Overview",324,"v"],
        ["VPC Overview",70,"v"],
        ["VPC Hands On",128,"h"],
        ["Subnet Overview",100,"v"],
        ["Subnet Hands On",233,"h"],
        ["Internet Gateways & Route Tables",73,"v"],
        ["Internet Gateways & Route Tables Hands On",422,"h"],
        ["Bastion Hosts",161,"v"],
        ["Bastion Hosts Hands On",302,"h"],
        ["NAT Instances",221,"v"],
        ["NAT Instances Hands On",358,"h"],
        ["NAT Gateways",227,"v"],
        ["NAT Gateways Hands On",183,"h"],
        ["Regional NAT Gateway",86,"v"],
        ["NACL & Security Groups",643,"v"],
        ["NACL & Security Groups Hands On",392,"h"],
        ["VPC Peering",126,"v"],
        ["VPC Peering Hands On",347,"h"],
        ["VPC Endpoints",345,"v"],
        ["VPC Endpoints Hands On",400,"h"],
        ["VPC Flow Logs",256,"v"],
        ["VPC Flow Logs Hands On + Athena",611,"h"],
        ["Site to Site VPN, Virtual Private Gateway & Customer Gateway",238,"v"],
        ["Site to Site VPN, Virtual Private Gateway & Customer Gateway Hands On",114,"h"],
        ["Direct Connect & Direct Connect Gateway",387,"v"],
        ["Direct Connect + Site to Site VPN",60,"v"],
        ["Transit Gateway",310,"v"],
        ["VPC Traffic Mirroring",130,"v"],
        ["IPv6 for VPC",199,"v"],
        ["IPv6 for VPC - Hands On",229,"h"],
        ["Egress Only Internet Gateway",188,"v"],
        ["Egress Only Internet Gateway Hands On",60,"h"],
        ["Section Cleanup",142,"v"],
        ["VPC Section Summary",306,"v"],
        ["Networking Costs in AWS",557,"v"],
        ["AWS Network Firewall",180,"v"],
        ["VPC Quiz",0,"q"],
      ] },
      { id: "saa-28", n: 28, title: "Disaster Recovery & Migrations", minutes: 44, pace: "deep", lectures: [
        ["Disaster Recovery in AWS",688,"v"],
        ["Elastic Disaster Recovery (DRS)",108,"v"],
        ["Database Migration Service (DMS)",314,"v"],
        ["Database Migration Service (DMS) - Hands On",274,"h"],
        ["RDS & Aurora Migrations",154,"v"],
        ["On-Premises Strategies with AWS",184,"v"],
        ["AWS Backup",190,"v"],
        ["AWS Backup - Hands On",265,"h"],
        ["Application Migration Service (MGN)",183,"v"],
        ["Transferring Large Datasets into AWS",174,"v"],
        ["VMware Cloud on AWS",108,"v"],
        ["Disaster Recovery & Migration Quiz",0,"q"],
      ] },
      { id: "saa-29", n: 29, title: "More Solution Architectures", minutes: 27, pace: "normal", lectures: [
        ["Event Processing in AWS",340,"v"],
        ["Caching Strategies in AWS",183,"v"],
        ["Blocking an IP Address in AWS",305,"v"],
        ["High Performance Computing (HPC) on AWS",405,"v"],
        ["EC2 Instance High Availability",409,"v"],
        ["More Solution Architectures Quiz",0,"q"],
      ] },
      { id: "saa-30", n: 30, title: "Other Services", minutes: 48, pace: "normal", lectures: [
        ["Other Services Section Introduction",36,"v"],
        ["CloudFormation Intro",211,"v"],
        ["CloudFormation - Hands On",512,"h"],
        ["CloudFormation - Service Role",201,"v"],
        ["Amazon SES",80,"v"],
        ["Amazon Pinpoint",112,"v"],
        ["SSM Session Manager",345,"v"],
        ["SSM Other Services",271,"v"],
        ["AWS Cost Explorer",129,"v"],
        ["AWS Cost Anomaly Detection",70,"v"],
        ["AWS Outposts",158,"v"],
        ["AWS Batch",185,"v"],
        ["Amazon AppFlow",83,"v"],
        ["AWS Amplify",119,"v"],
        ["Instance Scheduler on AWS",341,"v"],
        ["Other Services Quiz",0,"q"],
      ] },
      { id: "saa-31", n: 31, title: "WhitePapers and Architectures - AWS Certified Solutions Architect Associate", minutes: 15, pace: "normal", lectures: [
        ["WhitePaper Section Introduction",53,"v"],
        ["AWS Well-Architected Framework & Well-Architected Tool",367,"v"],
        ["AWS Trusted Advisor Overview + Hands-On",198,"h"],
        ["Examples of Architecture - AWS Certified Solutions Architect Associate",258,"v"],
        ["WhitePapers & Architectures Quiz",0,"q"],
      ] },
      { id: "saa-32", n: 32, title: "Preparing for the Exam + Practice Exam - AWS Certified Solutions Architect Assoc", minutes: 17, pace: "normal", lectures: [
        ["Exam Preparation - Section Introduction",31,"v"],
        ["State of Learning Checkpoint - AWS Certified Solutions Architect Associate",262,"v"],
        ["Exam Tips - AWS Certified Solutions Architect Associate",204,"v"],
        ["Links to Whitepapers",11,"a"],
        ["Exam Walkthrough and Signup",277,"v"],
        ["Save 50% on your AWS Exam Cost!",70,"v"],
        ["Get an Extra 30 Minutes on your AWS Exam - Non Native English Speakers only",64,"v"],
        ["How does the exam work?",100,"v"],
        ["Practice Exam - AWS Certified Solutions Architect Associate",0,"p"],
      ] },
      { id: "saa-33", n: 33, title: "Congratulations - AWS Certified Solutions Architect Associate", minutes: 9, pace: "trivial", lectures: [
        ["AWS Certification Paths",365,"v"],
        ["Congratulations",96,"v"],
        ["Bonus Lecture",73,"a"],
      ] },
    ],
  },
};

const PACE_SPEED = { trivial: 2, skim: 2, normal: 1.5, deep: 1.25 };
